exports.levels = [
  {
    map: [
      [
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
      ],
      [
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "path", nextCoords: [{ y: 1, x: 4 }] },
        { type: "path", nextCoords: [{ y: 1, x: 5 }] },
        { type: "path", nextCoords: [{ y: 1, x: 6 }] },
        { type: "path", nextCoords: [{ y: 1, x: 7 }] },
        { type: "path", nextCoords: [{ y: 2, x: 7 }] },
        { type: "grass" },
        { type: "grass" },
      ],
      [
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "path", nextCoords: [{ y: 1, x: 3 }] },
        { type: "grass" },
        { type: "grass" },
        { type: "building" },
        { type: "path", nextCoords: [{ y: 3, x: 7 }] },
        { type: "grass" },
        { type: "grass" },
      ],
      [
        { type: "path", nextCoords: [{ y: 3, x: 1 }] },
        { type: "path", nextCoords: [{ y: 3, x: 2 }] },
        { type: "path", nextCoords: [{ y: 3, x: 3 }] },
        { type: "path", nextCoords: [{ y: 2, x: 3 }] },
        { type: "grass" },
        { type: "path", nextCoords: [{ y: 4, x: 5 }] },
        { type: "path", nextCoords: [{ y: 3, x: 5 }] },
        { type: "path", nextCoords: [{ y: 3, x: 6 }] },
        { type: "grass" },
        { type: "grass" },
      ],
      [
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "building" },
        { type: "grass" },
        { type: "path", nextCoords: [{ y: 5, x: 5 }] },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
      ],
      [
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "path", nextCoords: [{ y: 5, x: 6 }] },
        { type: "path", nextCoords: [{ y: 5, x: 7 }] },
        { type: "path", nextCoords: [{ y: 5, x: 8 }] },
        { type: "path", nextCoords: [{ y: 5, x: 9 }] },
        { type: "path", nextCoords: [] },
      ],
      [
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "grass" },
        { type: "building" },
        { type: "grass" },
        { type: "grass" },
      ],
    ],
    waves: [
      { timer: 2, enemies: 5 },
      // { timer: 9, enemies: 4 },
      // { timer: 8, enemies: 3 },
    ],
    startingCoords: [
      {
        y: 3,
        x: 0,
      },
    ],
  },
  // {
  //   map: [
  //     [{ type: "grass" }, { type: "grass" }, { type: "grass" }],
  //     [
  //       { type: "path", nextCoords: [{ y: 1, x: 1 }] },
  //       { type: "path", nextCoords: [{ y: 1, x: 2 }] },
  //       { type: "path", nextCoords: [] },
  //     ],
  //     [{ type: "grass" }, { type: "grass" }, { type: "grass" }],
  //   ],
  //   waves: [
  //     { timer: 2, enemies: 5 },
  //     { timer: 9, enemies: 4 },
  //     { timer: 8, enemies: 3 },
  //   ],
  //   startingCoords: [
  //     {
  //       y: 1,
  //       x: 0,
  //     },
  //   ],
  // },
];
