exports.levels = [
  [
    [
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
    ],
    [
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "path", id: 5 },
      { type: "path", id: 6 },
      { type: "path", id: 7 },
      { type: "path", id: 8 },
      { type: "path", id: 9 },
      { type: "grass" },
      { type: "grass" },
    ],
    [
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "path", id: 4 },
      { type: "grass" },
      { type: "grass" },
      { type: "building" },
      { type: "path", id: 10 },
      { type: "grass" },
      { type: "grass" },
    ],
    [
      { type: "path", id: 0 },
      { type: "path", id: 1 },
      { type: "path", id: 2 },
      { type: "path", id: 3 },
      { type: "grass" },
      { type: "path", id: 13 },
      { type: "path", id: 12 },
      { type: "path", id: 11 },
      { type: "grass" },
      { type: "grass" },
    ],
    [
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "building" },
      { type: "grass" },
      { type: "path", id: 14 },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
    ],
    [
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "path", id: 15 },
      { type: "path", id: 16 },
      { type: "path", id: 17 },
      { type: "path", id: 18 },
      { type: "path", id: 19 },
    ],
    [
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "grass" },
      { type: "building" },
      { type: "grass" },
      { type: "grass" },
    ],
  ],
  [
    [{ type: "grass" }, { type: "grass" }, { type: "grass" }],
    [
      { type: "path", id: 0 },
      { type: "path", id: 1 },
      { type: "path", id: 2 },
    ],
    [{ type: "grass" }, { type: "grass" }, { type: "grass" }],
  ],
];
