export const settings = {
  FIELD_SIZE: 100,

  SPACE_BETWEEN: 4,

  TOWER_DEFAULT_SIZE: 60,
  TOWER_SCALE: 12,

  ENEMY_SIZE: 50,
  ENEMY_SCALE: 12,
  ENEMY_HITBOX: 30,
  ENEMY_HP: 100,
  ENEMY_SPEED: 4,
  ENEMY_MONEY: 100,

  TREE_CREATION_CHANCE: 0.5,
  TREE_SIZE: 40,
  TREE_MAX_SCALE: 40,
  TREE_MIN_SCALE: 30,

  HOUSE_CREATION_CHANCE: 0.2,
  HOUSE_DEFAULT_SIZE: 50,
  HOUSE_MAX_SCALE: 4,
  HOUSE_MIN_SCALE: 3,

  BARN_DEFAULT_SIZE: 500,
  BARN_MAX_SCALE: 9,
  BARN_MIN_SCALE: 9,

  CASTLE_DEFAULT_SIZE: 1000,
  CASTLE_MAX_SCALE: 6,
  CASTLE_MIN_SCALE: 5,

  BULLET_SIZE: 20,
  BULLET_SCALE: 2,
  BULLET_SPEED: 8,

  MESSAGE_TTL: 5000,
  COOKIE: "tower-defence",
};
