export const settings = {
  FIELD_SIZE: 100,
  TOWER_DEFAULT_SIZE: 50,
  SPACE_BETWEEN: 4,
  ENEMY_SIZE: 50,
  ENEMY_HITBOX: 30,
  ENEMY_HP: 100,
  ENEMY_SPEED: 4,
  ENEMY_MONEY: 100,
  BULLET_SIZE: 20,
  BULLET_SPEED: 8,
  MESSAGE_TTL: 5000,
  COOKIE: "tower-defence",
};
